# Generated by Django 3.0.3 on 2020-02-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
